### ISSUE TITLE
VG-200Dataset

### ISSUE THREAD

**Issue by hugh920** [HCPLab-SYSU/HCP-MLR-PL#5]
Dear author, where did you download the VG-200 data set you used in your paper? Or how is it generated?

**Comment by putao537** [comment]
> Dear author, where did you download the VG-200 data set you used in your paper? Or how is it generated?

Sorry for late reply.

As claimed in papers, we generate VG-200 dataset by merely considering the 200 most frequent categories on Visual Genome dataset.

Since we have already provided related code files and partial labels (details in "Preliminary" and "Common Issues" of REDEME), you may need to download images from [Visual Genome](https://visualgenome.org/).

Please feel free to reopen this issue if you still have any questions.

**Comment by hugh920** [comment]
> > Dear author, where did you download the VG-200 data set you used in your paper? Or how is it generated?
> 
> Sorry for late reply.
> 
> As claimed in papers, we generate VG-200 dataset by merely considering the 200 most frequent categories on Visual Genome dataset.
> 
> Since we have already provided related code files and partial labels (details in "Preliminary" and "Common Issues" of REDEME), you may need to download images from [Visual Genome](https://visualgenome.org/).
> 
> Please feel free to reopen this issue if you still have any questions.

Firstly, thank you very much for your reply. I have another question. What is the difference between SARB and SARB-journal in your open source code? Which is the more polished version?
